# Generated by Django 5.2.5 on 2025-08-12 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0002_alter_carmodel_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='year',
            field=models.DateField(),
        ),
    ]
