# Generated by Django 5.2.5 on 2025-08-12 13:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0003_alter_carmodel_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='dealer_id',
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='type',
            field=models.CharField(choices=[('SEDAN', 'Sedan'), ('SUV', 'SUV'), ('WAGON', 'Wagon')], default='SUV', max_length=10),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='year',
            field=models.IntegerField(default=2023, validators=[django.core.validators.MaxValueValidator(2023), django.core.validators.MinValueValidator(2015)]),
        ),
    ]
